# ─────────────────────────────────────────────────────────────────────
# Networking — use the default VPC / subnet (EC2 + EIP pattern)
# ─────────────────────────────────────────────────────────────────────
data "aws_vpc" "default" {
  default = true
}

data "aws_subnets" "default" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }
}

# ─────────────────────────────────────────────────────────────────────
# AMI — AWS Deep Learning Base GPU AMI (Ubuntu 22.04).
# Ships NVIDIA driver + CUDA preinstalled, so the bootstrap only needs to
# install a CUDA-build of torch. Avoids fragile in-instance driver builds.
# ─────────────────────────────────────────────────────────────────────
data "aws_ami" "dlami_gpu" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["Deep Learning Base OSS Nvidia Driver GPU AMI (Ubuntu 22.04)*"]
  }
  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
  filter {
    name   = "architecture"
    values = ["x86_64"]
  }
}

# ─────────────────────────────────────────────────────────────────────
# SSH key pair (generated by Terraform; private key saved locally + output)
# ─────────────────────────────────────────────────────────────────────
resource "tls_private_key" "ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "this" {
  key_name   = "${var.project_name}-key"
  public_key = tls_private_key.ssh.public_key_openssh
}

resource "local_sensitive_file" "private_key" {
  content         = tls_private_key.ssh.private_key_pem
  filename        = "${path.module}/${var.project_name}-key.pem"
  file_permission = "0600"
}

# ─────────────────────────────────────────────────────────────────────
# Security group
# ─────────────────────────────────────────────────────────────────────
resource "aws_security_group" "this" {
  name        = "${var.project_name}-sg"
  description = "Allow HTTP, HTTPS, and SSH"
  vpc_id      = data.aws_vpc.default.id

  ingress {
    description = "HTTP"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  ingress {
    description = "HTTPS"
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.ssh_allowed_cidr]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

# ─────────────────────────────────────────────────────────────────────
# IAM role — SSM Session Manager + CloudWatch agent
# (no app secrets needed: gemma-4-E2B-it is an ungated public download)
# ─────────────────────────────────────────────────────────────────────
data "aws_iam_policy_document" "assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "this" {
  name               = "${var.project_name}-role"
  assume_role_policy = data.aws_iam_policy_document.assume.json
}

resource "aws_iam_role_policy_attachment" "ssm_core" {
  role       = aws_iam_role.this.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_role_policy_attachment" "cw_agent" {
  role       = aws_iam_role.this.name
  policy_arn = "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
}

resource "aws_iam_instance_profile" "this" {
  name = "${var.project_name}-profile"
  role = aws_iam_role.this.name
}

# ─────────────────────────────────────────────────────────────────────
# EC2 instance (GPU)
# ─────────────────────────────────────────────────────────────────────
resource "aws_instance" "this" {
  ami                    = data.aws_ami.dlami_gpu.id
  instance_type          = var.instance_type
  subnet_id              = data.aws_subnets.default.ids[0]
  vpc_security_group_ids = [aws_security_group.this.id]
  key_name               = aws_key_pair.this.key_name
  iam_instance_profile   = aws_iam_instance_profile.this.name

  user_data_replace_on_change = true
  user_data = templatefile("${path.module}/user_data.sh.tpl", {
    region           = var.region
    project_name     = var.project_name
    repo_url         = var.repo_url
    git_ref          = var.git_ref
    domain           = var.domain
    acme_email       = var.acme_email
    app_port         = var.app_port
    torch_cuda_index = var.torch_cuda_index
    hf_token         = var.hf_token

    # Co-hosted Palm-Reader (consolidated onto this box)
    palmreader_enabled           = var.palmreader_enabled
    palmreader_project_name      = var.palmreader_project_name
    palmreader_repo_url          = var.palmreader_repo_url
    palmreader_git_ref           = var.palmreader_git_ref
    palmreader_domain            = var.palmreader_domain
    palmreader_app_port          = var.palmreader_app_port
    palmreader_max_body          = var.palmreader_max_body
    palmreader_hf_token          = var.palmreader_hf_token
    palmreader_deploy_public_key = var.palmreader_deploy_public_key
  })

  root_block_device {
    volume_size = var.root_volume_gb
    volume_type = "gp3"
    encrypted   = true
  }

  metadata_options {
    http_tokens   = "required" # IMDSv2 only
    http_endpoint = "enabled"
  }

  tags = {
    Name = var.project_name
  }
}

resource "aws_eip" "this" {
  instance = aws_instance.this.id
  domain   = "vpc"
  tags = {
    Name = "${var.project_name}-eip"
  }
}

# ─────────────────────────────────────────────────────────────────────
# CloudWatch alarms
# ─────────────────────────────────────────────────────────────────────
resource "aws_cloudwatch_metric_alarm" "status_check" {
  alarm_name          = "${var.project_name}-status-check-failed"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 2
  metric_name         = "StatusCheckFailed"
  namespace           = "AWS/EC2"
  period              = 60
  statistic           = "Maximum"
  threshold           = 0
  alarm_description   = "EC2 instance/system status check failed."
  dimensions = {
    InstanceId = aws_instance.this.id
  }
}

resource "aws_cloudwatch_metric_alarm" "cpu_high" {
  alarm_name          = "${var.project_name}-cpu-high"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 3
  metric_name         = "CPUUtilization"
  namespace           = "AWS/EC2"
  period              = 300
  statistic           = "Average"
  threshold           = 90
  alarm_description   = "Average CPU > 90% for 15 minutes."
  dimensions = {
    InstanceId = aws_instance.this.id
  }
}

# ─────────────────────────────────────────────────────────────────────
# GPU memory alarm + notifications
# This box co-hosts Past-Life + Palm-Reader on one A10G (~23GB), so free
# GPU memory is tight. Alarm on the CloudWatch-agent metric
# nvidia_smi_memory_used (published to the TodozeePastLife namespace by
# user_data step 8) to catch pre-OOM pressure. Notifications go to an SNS
# topic; add an email endpoint via var.alarm_email (confirm it manually).
# ─────────────────────────────────────────────────────────────────────
resource "aws_sns_topic" "alerts" {
  name = "${var.project_name}-alerts"
}

resource "aws_sns_topic_subscription" "alerts_email" {
  count     = var.alarm_email == "" ? 0 : 1
  topic_arn = aws_sns_topic.alerts.arn
  protocol  = "email"
  endpoint  = var.alarm_email
  # NOTE: email subscriptions require the recipient to click AWS's
  # confirmation link; Terraform cannot auto-confirm (stays "pending").
}

resource "aws_cloudwatch_metric_alarm" "gpu_memory_high" {
  alarm_name          = "${var.project_name}-gpu-memory-high"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 3
  datapoints_to_alarm = 3
  metric_name         = "nvidia_smi_memory_used"
  namespace           = "TodozeePastLife" # matches the CW-agent namespace in user_data
  period              = 60
  statistic           = "Maximum"
  threshold           = var.gpu_memory_alarm_threshold_mib
  treat_missing_data  = "notBreaching"
  alarm_description   = "GPU memory > ${var.gpu_memory_alarm_threshold_mib} MiB on the A10G (co-hosts Past-Life + Palm-Reader). Risk of CUDA OOM."
  # All four dimensions must match what the CW agent publishes, or the
  # alarm never binds to the metric.
  dimensions = {
    InstanceId = aws_instance.this.id
    name       = var.gpu_name
    index      = "0"
    arch       = var.gpu_arch
  }
  alarm_actions = [aws_sns_topic.alerts.arn]
  ok_actions    = [aws_sns_topic.alerts.arn]
}
